package tests;// Generated by Selenium IDE

import model.GroupData;
import org.junit.jupiter.api.*;

public class canCrateGroup  extends TestBase {

    @Test
    public void canCreateGroup() {
        TestBase.app.groups().createGroup(new GroupData("group name", "header", "footer") );
    }

    @Test
    public void canCreateGroupWithEmptyName() {
        TestBase.app.groups().createGroup(new GroupData());
    }

    @Test
    public void canCreateGroupWithEmptyNameOnly() {
        app.groups().createGroup(new  GroupData().withName("some name"));
    }
}
