package tests;// Generated by Selenium IDE

import model.GroupData;
import org.junit.jupiter.api.Test;

public class canDeleteGroup  extends TestBase {

    @Test
    public void canDeleteGroup() {
        app.groups().openGroupPage();
        if (app.groups().isGroupPresent()){
            app.groups().createGroup(new GroupData("", "", ""));
        }
        app.groups().removeGroup();


    }

}
